<?php

namespace Uni\Bundle\MarcaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * anunciosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class anunciosRepository extends EntityRepository
{
}
